name: test release workflow

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level2'




jobs:




#0
  dockerbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:


      - name: Checkout code
        uses: actions/checkout@master
        
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"


      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker-username }}
          password: ${{ env.docker-password }}
      -
        name: Build and push ${{ env.app-tag }}
        uses: docker/build-push-action@v3
        with:
          # context: .
          file: ${{ env.dockerfile-path }}
          push: true
          tags: ${{ env.docker-repo-name }}:${{ env.app-tag }}-v${{ steps.info.outputs.version }}






#3
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@master
        
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"
        

      - uses: asad-boutique/github-release@v2.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.info.outputs.version }}
          name: v${{ steps.info.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          allow_override: 'true'
          
